### ISSUE TITLE
License

### ISSUE THREAD

**Issue by pchaigno** [lolow/sublime-gams#7]
I would like to use your grammar for GAMS but I don't know what licensing terms you're distributing it under. Any chance you could pick one from here: http://choosealicense.com?

**Comment by lolow** [comment]
Thank you for your interest in my work. I don't want to license the GAMS grammar described in the json file I developed. You can read or copy as much as you want.

**Comment by pchaigno** [comment]
With the Berne convention, I believe your work is under copyright "by default" :/
If the opposite is not stated clearly, I can't use it. I'll find an other solution :-(
