### ISSUE TITLE
bad file path in Main.sublime-menu

### ISSUE THREAD

**Issue by ackinetics** [lolow/sublime-gams#8]
Awesome job on this code!!

I found a small path bug that caused an error when I try to open the Build-default file.  In Main.sublime-menu, Line 19 the path is "file": "${packages}/sublime-gams/Gams.sublime-build"  but it should be   "file": "${packages}/GAMS language/Gams.sublime-build"

**Comment by lolow** [comment]
thanks for spotting this! It is corrected.
