### ISSUE TITLE
The system cannot find the specified file

### ISSUE THREAD

**Issue by samarthiith** [lolow/sublime-gams#9]
![capture](https://cloud.githubusercontent.com/assets/9819174/15583385/d820877c-2375-11e6-902e-d59560edfc0e.PNG)

I much appreciate enabling the sublime for gams. However, I am not able to sort out the error. Would be grateful if you could help out. I have added gams in the environment variables.

Thanks!

**Comment by lolow** [comment]
I think the problem is the space in the directory (the full directory
designation: C:\Users...learning). Can you try to save the file in a
directory without space to see if it works in this case? Then I will try to
find a workaround.

**Comment by samarthiith** [comment]
It works now, but that was not the problem. I was incorrectly adding the environment variables.  
Thanks for the quick reply and creating this plugin.
